config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => 'registrations'}
  authenticate :user do
  	resources :games
  	get "/users/show_users" => "users#index"
  	get "/show_users/:id" => "users#show" , :as => :show_user
  	get "/buy_game" => "games#buy_game"
  end
  root to: "games#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buy.rb
class Buy < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/game.rb
class Game < ApplicationRecord
	has_many :buys
	validates :title,{
  		length: { minimum: 10,  maximum: 50 },
  		presence: true
		}
	validates :description,{
  		length: { minimum: 30 },
  		presence: true
		}
	validates :image_url,{
  		presence: true
		}

	def is_buy_by_the_user(user_id)
		buy = Buy.where(:user_id=> user_id).where(:game_id=>id)
		if buy.empty?
			return false
		else
			return true
		end
	end

end

app/models/user.rb
class User < ApplicationRecord
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	  validates :first_name,{
			length: { minimum: 3,  maximum: 30 },
			presence: true
		}
  	validates :last_name,{
  		length: { minimum: 3,  maximum: 30 },
  		presence: true
		}
  	validates :email,{
  		length: { maximum: 50 } ,
  		presence: true,
  		uniqueness: true
		}
	validates :password,{
		length: {minimum: 8}
	}
	has_many :buys


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :is_staff])
    #devise_parameter_sanitizer.for(:account_update) << :is_staff
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    search_param = params[:search]
    if search_param.nil?
      @games = Game.all
    else
      @games = Game.where("title like ?","%#{params[:search]}%").uniq.sort_by{'title ASC'}
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
    if current_user.is_staff == false
      redirect_to games_path
    end
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    if current_user.is_staff == false
      redirect_to games_path
    end
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def buy_game
    game_id = params[:game_id]
    buy = Buy.where(:user_id=>current_user.id).where(:game_id=>game_id)
    status = "fail"
    if buy.empty?
      gamee = Game.find(game_id)
      buyy = Buy.create
      buyy.user = current_user
      buyy.game = gamee
      if buyy.save
        status = "create"
      end
    else
      for x in buy
        x.destroy
      end
      status = "destroy"
    end
    
    jsonObject = {"text" => status}
    respond_to do |format|
      format.html
      format.json { render json: jsonObject }
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:title, :description, :image_url)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
 skip_before_filter :require_no_authentication, only: [:new, :create]
 before_filter :authenticate_user!
 
 def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
     redirect_to games_path
    else
     render :new
    end
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :is_staff)
  end

  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]


  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    #disculpe por la mala practica, esto deberia estar en otra vista, pero no tengo tiempo
    user_id = params[:id]
    @user_to_change = User.find(user_id)
    if current_user.is_staff == false
      actual_staff_status = @user_to_change.is_staff
      puts actual_staff_status
      if actual_staff_status
        #@user_to_change.update(is_staff: false)
        @user_to_change.is_staff = false
        @user_to_change.save
      else
        #@user_to_change.update(is_staff: true) 
        @user_to_change.is_staff = true
        @user_to_change.save
      end
    end
    redirect_to "/users/show_users"
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :is_staff)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/_form.html.erb
<%= form_for(game) do |f| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<%= form_tag(games_path, method: 'get', class: 'form-inline navbar-form navbar-left') do %>
    <%= search_field_tag 'search', params[:search], class: 'form-control', placeholder: 'Search'  %>
    <%= submit_tag "Submit", class: 'btn btn-primary', :name => nil %>
<% end %>

<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Image url</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.title %></td>
        <td><%= game.description %></td>
        <td><%= game.image_url %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td>
        <button onclick="buy_game(<%= game.id%>)" id= "button<%=game.id%>"  type="button" class="btn btn-primary"> comprar</button>
      </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%if current_user %>
  <%= link_to 'New Game', new_game_path %>
  <%= link_to 'Log out', destroy_user_session_path, :method => :delete %>
  <%= link_to 'Show users', "/users/show_users" %>
<% else %>
  <%= link_to 'Log in', new_user_session_path %>
  <%= link_to 'Sign up', new_user_registration_path %>
<%end %>

<script>

function buy_game(game_id){

  var button_id = "button"+game_id
  $.ajax({
      type: "GET",
      dataType: "json",
      url: '/buy_game',
      data: {
          game_id: game_id// < note use of 'this' here
      },
      success: function(json) {
          var response = json.text;
          alert(response);
          if (response == "destroy")
          {
            $('#button1').removeClass('btn btn-success');
            $('#button1').addClass('btn btn-primary');
          }
          else if (response == "create"){
            $('#button1').removeClass('btn btn-primary');
            $('#button1').addClass('btn btn-success');
          }
          
      },
      error: function(json) {
          alert("Necesitas estar registrado para comprar !!!")
      }
  });
}

</script>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @game.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @game.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @game.image_url %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vapor</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :is_staff %>
    <%= f.text_field :is_staff %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Is staff</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.is_staff %></td>
        <td><%= link_to 'change is_staff', show_user_path(id: user.id) %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<td><%= link_to 'Back', games_path %></td>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Is staff:</strong>
  <%= @user.is_staff %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>